### ISSUE TITLE
Do not install this if you want to revert back to old Unity GI !

### ISSUE THREAD

**Issue by K3rhos** [jiaozi158/UnitySSGIURP#8]
Everything in the title, do not install this if you plan to revert back to original Unity Realtime/Baked GI, I just removed the package and everything bcs it was not to my liking, I just wanted to test the look, reverted back all my settings, and now my lightmaps get generated pitch black !
I tried to clean GI cache in Unity, regenerated lighting, restarted the editor... no matter what I do my lighmaps get generated pitch black since I installed this package, one day of work thrown into the bin, I need to revert back to my yesterday backup due to that and need to reimport all the work I made today...

Just in case:
- Unity 2022.3.41f1
- URP 14

**Comment by K3rhos** [comment]
Okay after more testing it looks like it has only fucked the scene I was testing this package for some reason the other scenes I have can generate proper lightmaps, so I guess I will just reimport my scene elements into a fresh scene !

Fortunately my scene doesn't have too much stuff to import.

**Comment by jiaozi158** [comment]
Hi, I'm sorry to hear that!

Since SSGI is a screen space effect, it shouldn't be able to affect the scene after removing the package.

What will be left in the project is a "missing renderer feature" box, but that happens to all custom renderer features when deleting the script without removing it from all URP renderers first. (and it shouldn't affect baking)
![Missing Renderer Feature](https://github.com/user-attachments/assets/1eee3b45-7da5-423d-8294-3865f602680c)

This is a big problem for me, so I tried to reproduce it but baking seemed to work fine after removing the SSGI package.
![Baked GI](https://github.com/user-attachments/assets/6e3a0fe8-6028-42ea-ac0f-1498d16fd430)

I totally get your concerns when the baked lightmaps not working anymore, but I can't seem to reproduce it in the Relaxing Corner scene. (Unity 2022.3.37f1) So, I can’t explain or provide a solution for this.☹️

In addition to this, the only supported baked GI **will be** APV when using SSGI. If anyone plans to use SSGI in a lightmapped scene, I recommend unchecking **Override Ambient Lighting** in the renderer feature.

Anyway, thank you for trying it and I'm really sorry about this!

**Comment by K3rhos** [comment]
Honestly I have no idea why it did that, I had properly removed everything, SSGI from the renderer preset, and also from the global volume, like I said I also cleaned the GI cache, recreated a lighting scene profile etc... but not matter what I tried, my scene lightmaps were all generated pitch black after deleting the package !

That's not a big issue, since I was able to simply recreate a scene, deleting the previous one, reimport the exact same stuff I had saved in prefabs, and the lightmaps were all working properly again !

Maybe just Unity sometimes doing weird stuff...🤷

Btw, I installed your Volumetrics Clouds URP package (https://github.com/jiaozi158/UnityVolumetricCloudsURP) and this one is amazing and perfectly fit what I needed ! No issue with this one hehe.

Thx for responding so quickly, and sorry again for being so mad yesterday, I was a bit annoyed at the time lol ! Have a nice day.

**Comment by jiaozi158** [comment]
Thank you very much for your understanding, I will keep an eye on the lightmap baking issue in the future.

It's fine because when something goes wrong, we all want to solve it as quickly as possible, and that's why I try to reply quickly too.

Also, glad to hear that the volumetric clouds repo is helpful for your project! Feel free to discuss with me if there's any problem with the clouds.😉
